### ISSUE TITLE
Cannot get the package into a project via the Nuget package manager

### ISSUE THREAD

**Issue by ItPutsTheLotionInTheBasket** [matthewcrews/flips#43]
When I attempt to add this as a project, I get the following error:

 _Could not install package 'Flips 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.__

I also try to download the zip directly and build. When I do this, I can run the console test, however when I try to run the script flips-master\Flips\Scratchpad.fsx , I get the following errors: 

_error FS0229: Error opening binary file '..\flipsmaster\Flips.Examples\bin\x64\Release\netcoreapp3.1\google-ortools-native.dll': C:\Users\thrallL\Downloads\flips-master\Flips.Examples\bin\x64\Release\netcoreapp3.1\google-ortools-native.dll: bad cli header, rva 0_
and 

_error FS3160: Problem reading assembly 'flips-master\Flips.Examples\bin\x64\Release\netcoreapp3.1\google-ortools-native.dll': Processing of a script fragment has stopped because an exception has been raised_

**Comment by matthewcrews** [comment]
It sounds like your project you are trying to add it to is targeting the .NET Framework, not .NET Core. Could you try having it target .NET Core and run the project as an x64 app?

**Comment by ItPutsTheLotionInTheBasket** [comment]
That was it. Thank you.
