### ISSUE TITLE
Consider adding a gh-page

### ISSUE THREAD

**Issue by Shmew** [matthewcrews/flips#52]
As you add more features the README is going to get pretty big. As an example you can see the docs I have for [Fable.Jester](https://shmew.github.io/Fable.Jester/), and the [elmish-book](https://zaid-ajaj.github.io/the-elmish-book/).

**Comment by matthewcrews** [comment]
Love this thought! I need to look into that. The initial README just kept growing. I have never created a gh-page before but I'd like to figure it out.

**Comment by matthewcrews** [comment]
@Shmew Is there a walkthrough that you would recommend for creating docs like you have for Fable.Jester and elmish-book?

**Comment by Shmew** [comment]
[Here's a starter template](https://github.com/Zaid-Ajaj/docute-starter) and the [docute site](https://docute.org/).

**Comment by matthewcrews** [comment]
@Shmew Thanks for the recommendation. Docs are now up! docute was really easy to use.
