### ISSUE TITLE
About F# code formatting guideline

### ISSUE THREAD

**Issue by wxinix** [matthewcrews/flips#87]
If I would like to contribute to this (great) project, what F# code formatting style should I follow?  

I am looking at this [guideline](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting).  But it seems you are not exactly following it.

**Comment by matthewcrews** [comment]
I try to follow those guidelines. If you find a place where I am being inconsistent, please feel free to point it out. I always appreciate feedback on my style.

**Comment by wxinix** [comment]
I found through out the flips code, this [style guideline](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#right-pad-function-argument-type-annotations) is not followed.

Nothing serious, though.

**Comment by matthewcrews** [comment]
Thanks! I'll get that addressed!

**Comment by wxinix** [comment]
Thank you, and thank you for this great project.
